Add dedicated policy for agents started through the vm extension
elastic/azure-vm-extension pull request #47
Opened 2022-02-01 19:52 UTC by kaiyan-sheng

This PR is to change Azure VM extension from checking the Default policy created by Kibana to create a dedicated policy for azure VM extension.

closes: https://github.com/elastic/azure-vm-extension/issues/11

2022-02-01 20:52 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fazure-vm-extension-mbp%2FPR-47/detail/PR-47/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fazure-vm-extension-mbp%2FPR-47/detail/PR-47/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fazure-vm-extension-mbp%2FPR-47/detail/PR-47/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fazure-vm-extension-mbp%2FPR-47/detail/PR-47/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://null_47.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-02-01T19:43:04.270Z&rangeTo=2022-02-01T20:03:04.270Z&transactionName=Beats/azure-vm-extension-mbp/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=d8a17b716dcb86b6c4c09f6b3d372bda&transactionId=3603db129f1ae9e2)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats



* Reason: `null`


* Start Time: 2022-02-01T19:53:04.270+0000


* Duration: 60 min 35 sec


* Commit: 2feca1a911f10f2e2f25ce9985a643d9632ecc6c



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 24  |
| Skipped      | 0 |
| Total        | 24   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-02-03 07:34 UTC, juliaElastic commented on src/handler/linux/enable.sh
> +  jsonResult=$(curl ${KIBANA_URL}/api/fleet/enrollment-api-keys -H 'Content-Type: application/json' -H 'kbn-xsrf: true' -u "$cred" )
`enrollment-api-keys` is deprecated and has changed to `enrollment_api_keys`, please use that: https://petstore.swagger.io/?url=https://raw.githubusercontent.com/elastic/kibana/main/x-pack/plugins/fleet/common/openapi/bundled.json#/default/get-enrollment-api-keys

2022-02-03 07:37 UTC, juliaElastic commented on src/handler/windows/scripts/enable.ps1
> +                        $azurePolicy = Get-AnyActive-Policy $keyValue
I'm not sure it's right to fall back to any active policy here

2022-02-03 07:38 UTC, juliaElastic commented
Overall looks good from Fleet perspective, commented a few things

2022-02-03 08:56 UTC, masci requested changes
Didn't go through the powershell section, let's figure out the correct behaviour on linux first and we'll translate to ps later

2022-02-03 08:56 UTC, masci commented on src/handler/linux/enable.sh
> +  if [[ "$ID" = "" ]]; then
Since it's called twice we can move this block into a function like `get_all_policies`

2022-02-03 08:56 UTC, masci commented on src/handler/linux/enable.sh
> +  if [[ "$ID" = "" ]]; then
why renaming? I think `POLICY_ID` is a better name but in any case we should stay consistent

2022-02-03 08:56 UTC, masci commented on src/handler/linux/helper.sh
> +    ID=$(_jq '.id')
this can just be `ID=$policy_id` so you spare a process fork

2022-02-03 08:56 UTC, masci commented on src/handler/linux/helper.sh
> +  result=$(curl -X POST "${KIBANA_URL}"/api/fleet/agent_policies?sys_monitoring=true -H 'Content-Type: application/json' -H 'kbn-xsrf: true' -u "$cred" -d '{"name":"Azure VM extension policy","descri
Let's put the name of the policy in a variable like `POLICY_NAME`

2022-02-03 08:56 UTC, masci commented on src/handler/linux/helper.sh
> +  if [[ "$name" == *"Azure VM extension"* ]] && [[ "$status" == "active" ]] && [[ "$policy_id" != *"elastic-agent-on-cloud"* ]]; then
I think we should be strict here - now that we have a dedicate policy for the VM, why matching similar names? This might cause subtle, unexpected behaviour.

2022-02-03 08:56 UTC, masci commented on src/handler/linux/helper.sh
> +  id=$(_jq '.id')
let's stay consistent with variable naming, in similar places this is `policy_id`

2022-02-03 08:56 UTC, masci commented on src/handler/linux/helper.sh
> +    ID=$(_jq '.id')
same as above, you can spare a call to `jq`

2022-02-03 08:56 UTC, masci commented on src/handler/linux/enable.sh
>      get_any_active_policy "\${jsonResult}"
Now that we have a dedicated policy, this should be an error instead

2022-02-03 09:18 UTC, aspacca commented
as far as I can see we still fallback to `any` policy if we fail to create/find the specific azure policy, that was the previous behaviour as well if no `default` policy was found.
while the behaviour won't change I would expect it was most likely that the `default` policy was rarely missing and rarely without `sys_monitoring`. I would expect such overall positive scenario will change in the new release without the `default` policy and I wonder if we should avoid to fallback to `any` policies.
Is there any way to query for available policies with `sys_monitoring` enabled?

2022-02-03 09:21 UTC, aspacca commented
according to Microsoft documentation publishing a new version of the handler will trigger the update command: the workflow will finally run the enable command with the new policy logic.

is there any corner case where a previous version of the handler will keep running on a VM without being updated?

2022-02-03 09:22 UTC, aspacca commented on src/handler/windows/HandlerManifest.json
> -[{
why this file is removed?

2022-02-03 14:53 UTC, kaiyan-sheng commented on src/handler/windows/HandlerManifest.json
> -[{
It's renamed to `HandlerEnvironment.json` because in the windows code, it's looking for HandlerEnvironment instead. But for linux, it's still HandlerManifest.json. Instead of renaming this one, I should keep the old name and change the windows code to look for the correct file.

2022-02-04 00:13 UTC, kaiyan-sheng commented on src/handler/linux/enable.sh
> +  log "INFO" "[Enroll_ElasticAgent] enrollment_token is $enrollment_token"
Good point! @juliaElastic do you know if it's OK to log the enrollment token?

2022-02-04 04:34 UTC, kaiyan-sheng commented on src/handler/windows/scripts/enable.ps1
> +                        $azurePolicy = Get-AnyActive-Policy $keyValue
Yep I think we should never fall back to other policies now with a dedicated azure policy created. Thanks!!

2022-02-04 04:48 UTC, kaiyan-sheng commented on src/handler/linux/enable.sh
> +  if [[ "$ID" = "" ]]; then
Yeah you are right. I was using two separate variable names because the ID from the `api/fleet/agent_policies` API is different comparing with `api/fleet/enrollment-api-keys` ID. But making them consistent is probably easier to read.

2022-02-04 05:33 UTC, kaiyan-sheng commented
@aspacca I removed the fallback in the latest commits because the dedicated azure policy should always be there, either already exists or created by the VM extension, so no more fallback to `Default` or any other active policies. I don't see a way to query for available policies with `sys_monitoring` enabled right now. The only given path for agent_policies API is to query with a given agent policy ID. 

> is there any corner case where a previous version of the handler will keep running on a VM without being updated?

I don't see it (yet). When installing VM extension on an old VM with a new Elastic cluster, still should be the latest VM extension being used.

2022-02-04 08:19 UTC, juliaElastic commented on src/handler/linux/enable.sh
> +  log "INFO" "[Enroll_ElasticAgent] enrollment_token is $enrollment_token"
I would think so, as it is visible on UI as well (not encrypted)

2022-02-04 10:20 UTC, joshdover commented on src/handler/linux/enable.sh
> +  log "INFO" "[Enroll_ElasticAgent] enrollment_token is $enrollment_token"
Where do these logs go to / output to? In general, these tokens should only be visible to a user who has access to use/configure/administer Fleet. If these are being logged on the VM hosts, I think that's likely fine, though I wonder the value of logging the entire token value. What if we only showed the last 4 characters and used `X` for the other characters?

2022-02-04 18:55 UTC, kaiyan-sheng commented on src/handler/linux/enable.sh
> +  jsonResult=$(curl ${KIBANA_URL}/api/fleet/enrollment-api-keys -H 'Content-Type: application/json' -H 'kbn-xsrf: true' -u "$cred" )
We will make this change in a separate PR and make a separate release for it.

2022-02-04 18:56 UTC, kaiyan-sheng commented on src/handler/linux/enable.sh
> +  log "INFO" "[Enroll_ElasticAgent] enrollment_token is $enrollment_token"
@joshdover On linux vm, these logs go to `./var/log/azure/Elastic.ElasticAgent.linux/es-agent.log` on the VM.

2022-02-07 12:15 UTC, joshdover commented on src/handler/linux/enable.sh
> +  log "INFO" "[Enroll_ElasticAgent] enrollment_token is $enrollment_token"
Great, that's what I expected. I think it'd probably still be safer to not log the verbatim key and instead only log the last 4 digits.

@ph do you know if we log enrollment keys today when enrolling an Agent? Should we avoid this for the Azure extension?

2022-02-08 08:05 UTC, juliaElastic commented on src/handler/windows/scripts/helper.ps1
>  function Get-AnyActive-Policy($content){
nit: could be removed if unused

2022-02-08 08:05 UTC, juliaElastic approved these changes
LGTM

2022-02-22 18:14 UTC, kaiyan-sheng commented on src/handler/linux/enable.sh
> +  log "INFO" "[Enroll_ElasticAgent] enrollment_token is $enrollment_token"
Since the original behavior of azure vm extension is to log the full enrollment token. I will keep it as is for now and if we decide later on to change it, I can create a separate PR for that.

2022-02-22 18:20 UTC, merged